config/routes.rb
St::Application.routes.draw do
  root :to => 'Pages#home'
  
  get "about" => "pages#about"

  get "gift" => "pages#gift"

  get "love" => "pages#love"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def gift
  end

  def love
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "Это приложение написано с любовью, так как все мое обучение Ruby проходит с мыслями о моей девочке", "#" %>
		by <%= link_to "Твоя вторая половинка", "http://ligeo.ru" %>
	</small>
</div>

app/views/layouts/_header.html.erb


<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="localhost:3000">St. Valentine's Day</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<!-- <ul class="nav">
	        
		</ul> -->
		<ul class="nav pull-left">
          <!-- search form in header -->
          <li>
            <form class="navbar-search">
            
            </form> 
          </li>
         <li><%= link_to "Home", root_path %></li>
		</ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Valentine</title>
   <%= stylesheet_link_tag    "application", :media => "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<form class ="hero-unit">
  <fieldset>
    <legend>Ты самая красивая девушка на этом свете</legend>
    <p> Маша, наша встреча это не случайность, это судьба, два человека на столько <br>
    похожие друг на друга должны быть вместе, расстояние этому не преграда.<br>
	Я сделаю все возможное для того, чтобы переехать в тебе скорее!!! <br>
	Но так как в этот день меня нет с тобой рядом, я решил подготовить такой<br>
	необычный подарок</p>

    <p>
	<%= link_to "Хочу скорее свой подарок", gift_path, class: "btn btn-primary btn-large" %>
</p>
  </fieldset>
</form>

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href= "#tab1"  data-toggle="tab">Мои статьи</a></li>
    <li><a href= "#tab2"  data-toggle="tab">Статьи моих друзей</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <p>Здесь хранятся мои рассказы.</p>
    </div>
    <div class="tab-pane" id="tab2">
      <p>Здесь хранятся чужие истории.</p>
    </div>
  </div>
</div>
  

  <address>
  <strong>Medium, Inc.</strong><br>
  Novoslobodskaya, 600<br>
  Moscow, 125466<br>
  <abbr title="Phone">P:</abbr> (495) 456-7890
</address>
 
<address>
  <strong>Full Name</strong><br>
  <a href="mailto:#">info@medium.com</a>
</address>

</body>
</html>

app/views/pages/gift.html.erb
<div class="row">
  <div class="span10">
   <div class="thumbnail">
      <img src="http://cs319328.userapi.com/v319328549/4cf0/BVP7zneWSQg.jpg" >
    </div>
    <p>
	<%= link_to "Малышка, это еще не все", about_path, class: "btn btn-primary btn-large" %>
	</p>
  </div>
</div>

<!-- <div class="row">
  	<div class="span9 offset 7">
  	<h3>С днем всех влюбленных, Машуля</h3>
  	<img src="http://cs319328.userapi.com/v319328549/4cf0/BVP7zneWSQg.jpg">
    <button class="btn btn-primary">Читать</button>
    </div>
</div>
-->

app/views/pages/home.html.erb
<div class="hero-unit">
<h1>Доброе утро, моя девочка :-*</h1>

<p>
Сегодня необычный день, день всех влюбленных, мы пока не говорим друг другу, что мы людим,
но я точно чувствую, что это любовь.
Сегодня я приготовил для тебя несколько подарков.
</p>
<p>
	<%= link_to "Интересно узнать, что дальше?", about_path, class: "btn btn-primary btn-large" %>
</p>
</div>

app/views/pages/love.html.erb
<h1>Pages#love</h1>
<p>Find me in app/views/pages/love.html.erb</p>